# .gitlab-ci.yml

stages:
  - dev
  - stage
  - prod

variables:
  DOCKER_HOST: tcp://docker:2375
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

services:
  - docker:dind

dev:
  stage: dev
  script:
    - docker-compose -f docker-compose.dev.yml build
    - docker-compose -f docker-compose.dev.yml up -d

stage:
  stage: stage
  script:
    - docker-compose -f docker-compose.stage.yml build
    - docker-compose -f docker-compose.stage.yml up -d

prod:
  stage: prod
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml up -d