version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=prod_database_host
      - DB_PORT=prod_database_port
      - DB_USER=prod_database_user
      - DB_PASSWORD=prod_database_password
      - DB_NAME=prod_database_name

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000